COMPOSE ?= docker compose
DEV_COMPOSE = $(COMPOSE) -f docker-compose.dev.yml
RELEASE_COMPOSE = $(COMPOSE) -f docker-compose.release.yml
LEPTOS_TAILWIND_VERSION ?= v4.2.1
TAILWIND_VERSION_ENV = LEPTOS_TAILWIND_VERSION=$(LEPTOS_TAILWIND_VERSION)
CARGO_LEPTOS_VERSION ?= 0.3.6

ifneq (,$(wildcard .env))
include .env
export
endif

.PHONY: \
	help check \
	bootstrap-local \
	env-init \
	test \
	run run-debug run-release \
	web-watch web-build web-build-release tailwind-preflight web-assets-check ui-class-check \
	prompt-assets-check \
	dev-build dev-up dev-down dev-clean dev-logs dev-all-logs \
	release-build release-up release-down release-clean release-logs release-all-logs \
	hosts-rehearse-db-migrations dev-rehearse-db-migrations release-rehearse-db-migrations \
	wait-health health build-release docker-build \
	docs-check sweep

env-init: ## Ensure .env exists and SESSION_SECRET is generated if missing/placeholder
	@set -eu; \
	if [ ! -f .env ]; then \
		cp .env.example .env; \
		echo "Created .env from .env.example"; \
	fi; \
	if ! command -v openssl >/dev/null 2>&1; then \
		echo "openssl is required to generate SESSION_SECRET but was not found in PATH"; \
		exit 1; \
	fi; \
	current_value=$$(grep -E '^SESSION_SECRET=' .env | tail -n 1 | cut -d '=' -f2- || true); \
	current_trimmed=$$(printf '%s' "$$current_value" | tr -d '[:space:]'); \
	needs_secret=0; \
	if [ -z "$$current_trimmed" ]; then \
		needs_secret=1; \
	else \
		case "$$current_trimmed" in \
			\<replace*|\<auto-generated*|\"\"|\'\') needs_secret=1 ;; \
			*) needs_secret=0 ;; \
		esac; \
	fi; \
	if [ "$$needs_secret" -eq 1 ]; then \
		new_secret=$$(openssl rand -base64 64 | tr -d '\n'); \
		if grep -qE '^SESSION_SECRET=' .env; then \
			awk -v secret="$$new_secret" 'BEGIN{done=0} \
				/^SESSION_SECRET=/{if(!done){print "SESSION_SECRET=" secret; done=1} next} \
				{print} \
				END{if(!done) print "SESSION_SECRET=" secret}' .env > .env.tmp; \
			mv .env.tmp .env; \
		else \
			printf "\nSESSION_SECRET=%s\n" "$$new_secret" >> .env; \
		fi; \
		echo "Generated SESSION_SECRET in .env"; \
	else \
		echo "Preserved existing SESSION_SECRET in .env"; \
	fi

bootstrap-local: ## Install rustup, repo-pinned toolchain/target, cargo-binstall, and cargo-leptos
	@set -eu; \
	if ! command -v rustup >/dev/null 2>&1; then \
		echo "rustup not found; installing rustup..."; \
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal; \
	fi; \
	cargo_home=$${CARGO_HOME:-$$HOME/.cargo}; \
	mkdir -p "$$cargo_home/bin"; \
	export PATH="$$cargo_home/bin:$$PATH"; \
	echo "Ensuring wasm32-unknown-unknown target is installed..."; \
	rustup target add wasm32-unknown-unknown; \
	tmp_dir=$$(mktemp -d); \
	trap 'rm -rf "$$tmp_dir"' EXIT; \
	if ! command -v cargo-binstall >/dev/null 2>&1; then \
		echo "Installing cargo-binstall from prebuilt release..."; \
		curl -L --proto '=https' --tlsv1.2 -sSf \
			https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz \
			-o "$$tmp_dir/cargo-binstall.tgz"; \
		tar -xzf "$$tmp_dir/cargo-binstall.tgz" -C "$$tmp_dir"; \
		install -m 0755 "$$tmp_dir/cargo-binstall" "$$cargo_home/bin/cargo-binstall"; \
	else \
		echo "cargo-binstall already installed; skipping install."; \
	fi; \
	installed_leptos_version=$$(cargo leptos --version 2>/dev/null | awk '{print $$2}' || true); \
	if [ "$$installed_leptos_version" = "$(CARGO_LEPTOS_VERSION)" ]; then \
		echo "cargo-leptos v$(CARGO_LEPTOS_VERSION) already installed; skipping install."; \
	else \
		echo "Installing cargo-leptos v$(CARGO_LEPTOS_VERSION) via cargo-binstall..."; \
		cargo binstall -y cargo-leptos@$(CARGO_LEPTOS_VERSION); \
	fi; \
	echo "Tool versions:"; \
	rustup --version | head -n 1; \
	rustc --version; \
	cargo --version; \
	cargo-binstall -V; \
	cargo leptos --version

sweep: ## Prune old build artifacts to reclaim disk
	@echo "Disk before:"
	@df -h /
	@echo "---"
	@cargo sweep --maxsize 20GB 2>&1 || echo "Note: cargo sweep not installed. Run: cargo install cargo-sweep"
	@echo "---"
	@echo "Disk after:"
	@df -h /
	@echo
	@echo "Finelor - Your own accounting department, on autopilot"
	@echo
	@echo "Options:"
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z0-9_-]+:.*?## / {printf "\033[36m%-48s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
	@echo

help: ## Show available make targets
	@echo "Finelor - Your own accounting department, on autopilot"
	@echo
	@echo "Options:"
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z0-9_-]+:.*?## / {printf "\033[36m%-48s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
	@echo

check: ## Run baseline local checks (fmt, test, clippy)
	cargo fmt -- --check
	cargo test
	cargo clippy --all-targets -- -D warnings

test: ## Run all Rust tests and clean file-backed SQLite temp artifacts
	cargo test
ifeq ($(OS),Windows_NT)
	@powershell -NoProfile -ExecutionPolicy Bypass -Command "\
	$$targets = @('finelor-it-*.db','finelor-it-*.db-wal','finelor-it-*.db-shm'); \
	$$roots = @($$env:TEMP, $$env:TMP, [System.IO.Path]::GetTempPath()) | Where-Object { $_ } | Select-Object -Unique; \
	foreach ($$root in $$roots) { foreach ($$pattern in $$targets) { Get-ChildItem -Path $$root -Filter $$pattern -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue } }; \
	Write-Output 'Test temp DB artifacts cleaned from Windows temp directories.'"
else
	@set -eu; \
	tmp_root="$${TMPDIR:-/tmp}"; \
	rm -f "$$tmp_root"/finelor-it-*.db "$$tmp_root"/finelor-it-*.db-wal "$$tmp_root"/finelor-it-*.db-shm 2>/dev/null || true; \
	rm -f /tmp/finelor-it-*.db /tmp/finelor-it-*.db-wal /tmp/finelor-it-*.db-shm 2>/dev/null || true; \
	echo "Test temp DB artifacts cleaned from $$tmp_root and /tmp"
endif

ui-class-check: ## Ensure Tailwind/DaisyUI classes stay inside the internal UI library
	@echo "Checking web UI class boundaries..."
	@leaks=$$(rg -n 'class(:[A-Za-z0-9_-]+)?\s*=\s*"' src/web \
		--glob '!src/web/components/ui/**' \
		-S || true); \
	if [ -n "$$leaks" ]; then \
		echo "Raw class strings are only allowed in src/web/components/ui/**:"; \
		echo "$$leaks"; \
		exit 1; \
	fi
	@leaks=$$(rg -n 'class:|class=format!\(' src/web \
		--glob '!src/web/components/ui/**' \
		-S || true); \
	if [ -n "$$leaks" ]; then \
		echo "Dynamic Tailwind/DaisyUI class assembly is only allowed in src/web/components/ui/**:"; \
		echo "$$leaks"; \
		exit 1; \
	fi
	@echo "UI class boundary passed."

prompt-assets-check: ## Ensure required prompt assets exist and config points to existing files
	@set -eu; \
	required_files="\
assets/prompts/sweden/vision_agent.md \
assets/prompts/sweden/accountant_agent.md \
assets/prompts/_shared/assistant_agent_soul.md \
assets/prompts/INSTRUCTIONS.md"; \
	for f in $$required_files; do \
		if [ ! -f "$$f" ]; then \
			echo "Missing prompt asset: $$f"; \
			exit 1; \
		fi; \
	done; \
	for key in vision_prompt_path accountant_prompt_path assistant_soul_prompt_path; do \
		path=$$(sed -n "s|^[[:space:]]*$$key:[[:space:]]*\"\\([^\"]*\\)\".*|\\1|p" config.yaml | head -n 1); \
		if [ -z "$$path" ]; then \
			echo "Missing or unparsable config key in config.yaml: $$key"; \
			exit 1; \
		fi; \
		if [ ! -f "$$path" ]; then \
			echo "Configured prompt path does not exist ($$key): $$path"; \
			exit 1; \
		fi; \
	done; \
	echo "Prompt assets check passed."

docs-check: ## Validate docs/task metadata and current Phase 1 scope guards
	@echo "Checking current docs exist..."
	@test -f README.md
	@test -f AGENTS.md
	@test -f docs/overview.md
	@echo "Docs checks passed."

# -----------------------------------------------------------------------------
# Host-run app workflow
# -----------------------------------------------------------------------------
tailwind-preflight: ## Fail early if an incompatible global tailwindcss would shadow cargo-leptos
	@bin=$$(command -v tailwindcss 2>/dev/null || true); \
	if [ -n "$$bin" ]; then \
		version=$$(tailwindcss --version 2>&1 || true); \
		case "$$version" in \
			*"$(LEPTOS_TAILWIND_VERSION)"*) ;; \
			*) \
				echo "Found global tailwindcss at $$bin, but this project expects $(LEPTOS_TAILWIND_VERSION)."; \
				echo "cargo-leptos checks PATH before its managed cache, so remove or update that binary before running this target."; \
				echo "Detected version output: $$version"; \
				exit 1; \
				;; \
		esac; \
	fi

run: env-init tailwind-preflight ## Run host app through cargo-leptos watch
	$(TAILWIND_VERSION_ENV) cargo leptos watch

run-debug: env-init tailwind-preflight ## Run host app through cargo-leptos watch with RUST_LOG=debug
	RUST_LOG=debug $(TAILWIND_VERSION_ENV) cargo leptos watch

run-release: env-init web-build-release ## Build release web assets and run release app once
	./target/release/finelor

web-watch: env-init tailwind-preflight ## Run cargo-leptos watch with SSR + hydration
	$(TAILWIND_VERSION_ENV) cargo leptos watch

web-build: tailwind-preflight ## Build Leptos SSR server + hydrated WASM assets
	$(TAILWIND_VERSION_ENV) cargo leptos build
	$(MAKE) web-assets-check

web-build-release: tailwind-preflight ## Build Leptos SSR server + hydrated WASM assets in release mode
	$(TAILWIND_VERSION_ENV) cargo leptos build --release
	$(MAKE) web-assets-check

web-assets-check: ## Verify generated Leptos JS/WASM assets agree
	@pkg_dir=target/site/pkg; \
	css_file="$$pkg_dir/finelor.css"; \
	js_file=$$(find "$$pkg_dir" -maxdepth 1 -type f -name '*.js' | head -n 1); \
	if [ ! -s "$$css_file" ]; then \
		echo "Generated Leptos CSS asset missing or empty: $$css_file"; \
		exit 1; \
	fi; \
	if ! rg -q "\\.card" "$$css_file"; then \
		echo "Generated CSS is missing DaisyUI card styles: $$css_file"; \
		exit 1; \
	fi; \
	if ! rg -q "\\.btn" "$$css_file"; then \
		echo "Generated CSS is missing DaisyUI button styles: $$css_file"; \
		exit 1; \
	fi; \
	if ! rg -q "\\.grid" "$$css_file"; then \
		echo "Generated CSS is missing Tailwind utility styles: $$css_file"; \
		exit 1; \
	fi; \
	if [ -z "$$js_file" ]; then \
		echo "No generated Leptos JS asset found in $$pkg_dir"; \
		exit 1; \
	fi; \
	asset_stem=$$(basename "$$js_file" .js); \
	hydration_wasm="$$asset_stem.wasm"; \
	if [ ! -f "$$pkg_dir/$$hydration_wasm" ]; then \
		echo "Generated Leptos hydration WASM asset missing: $$pkg_dir/$$hydration_wasm"; \
		echo "Found JS asset: $$js_file"; \
		exit 1; \
	fi; \
	if ! rg -q "export function hydrate\\(" "$$js_file"; then \
		echo "Generated Leptos JS asset does not export hydrate(): $$js_file"; \
		exit 1; \
	fi; \
	if ! rg -q "module_or_path" "$$js_file"; then \
		echo "Generated Leptos JS asset does not accept explicit module_or_path: $$js_file"; \
		exit 1; \
	fi; \
	echo "Leptos assets verified: $$asset_stem.js exports hydrate(), uses $$hydration_wasm, and CSS contains Tailwind/DaisyUI"

# -----------------------------------------------------------------------------
# Full Docker development stack
# -----------------------------------------------------------------------------
dev-build:
	$(DEV_COMPOSE) build app

dev-up: env-init dev-build ## Build and start development app container
	$(DEV_COMPOSE) up -d app

dev-down: ## Stop development app container without removing containers or volumes
	$(DEV_COMPOSE) stop app

dev-clean: ## Stop and clean development stack and
	$(DEV_COMPOSE) down -v

dev-logs: ## Tail app development stack logs
	$(DEV_COMPOSE) logs -f app

dev-all-logs: ## Tail development app logs
	$(DEV_COMPOSE) logs -f app

# -----------------------------------------------------------------------------
# Release-style local stack
# -----------------------------------------------------------------------------
release-build: ## Build release app image
	$(RELEASE_COMPOSE) build app

release-up: env-init release-build ## Build and start release app container
	$(RELEASE_COMPOSE) up -d app

release-down: ## Stop release app container without removing containers or volumes
	$(RELEASE_COMPOSE) stop app

release-clean: ## Stop and clean release-style stack
	$(RELEASE_COMPOSE) down -v

release-logs: ## Tail app release-style stack logs
	$(RELEASE_COMPOSE) logs -f app

release-all-logs: ## Tail release-style app logs
	$(RELEASE_COMPOSE) logs -f app

# -----------------------------------------------------------------------------
# Common helpers
# -----------------------------------------------------------------------------
wait-health:
	@echo "Waiting for app health endpoint..."
	@for i in $$(seq 1 90); do \
		if curl --fail --silent http://localhost:3000/health >/dev/null 2>&1; then \
			echo "App is healthy"; \
			exit 0; \
		fi; \
		sleep 2; \
	done; \
	echo "App health check failed"; \
	exit 1

health: ## Call the app health endpoint once
	curl --fail --silent http://localhost:3000/health && echo

build-release: web-build-release ## Build Leptos SSR server + hydrated WASM assets locally with --release

docker-build: release-build

hosts-rehearse-db-migrations: ## Clone the host/local SQLite DB and rehearse all pending repo migrations on the copy
	@set -eu; \
	source_db="$(DATABASE_PATH)"; \
	if [ -z "$$source_db" ]; then \
		source_db=".finelor/db/finelor.db"; \
	fi; \
	python3 scripts/check_db_migrations.py \
		--source-db "$$source_db" \
		--label host

dev-rehearse-db-migrations: ## Copy the running dev Docker DB and rehearse all pending repo migrations on the copy
	@set -eu; \
	container_id="$$( $(DEV_COMPOSE) ps -q app )"; \
	if [ -z "$$container_id" ]; then \
		echo "Development app container is not running. Start it with 'make dev-up' first."; \
		exit 1; \
	fi; \
	stamp="$$(date +%Y%m%d-%H%M%S)"; \
	output_dir=".migration-checks/dev-$$stamp"; \
	mkdir -p "$$output_dir"; \
	source_copy="$$output_dir/finelor-live-source.db"; \
	docker cp "$$container_id:/app/.finelor/db/finelor.db" "$$source_copy"; \
	python3 scripts/check_db_migrations.py \
		--source-db "$$source_copy" \
		--output-dir "$$output_dir" \
		--label dev-docker

release-rehearse-db-migrations: ## Copy the running release Docker DB and rehearse all pending repo migrations on the copy
	@set -eu; \
	container_id="$$( $(RELEASE_COMPOSE) ps -q app )"; \
	if [ -z "$$container_id" ]; then \
		echo "Release app container is not running. Start it with 'make release-up' first."; \
		exit 1; \
	fi; \
	stamp="$$(date +%Y%m%d-%H%M%S)"; \
	output_dir=".migration-checks/release-$$stamp"; \
	mkdir -p "$$output_dir"; \
	source_copy="$$output_dir/finelor-live-source.db"; \
	docker cp "$$container_id:/app/.finelor/db/finelor.db" "$$source_copy"; \
	python3 scripts/check_db_migrations.py \
		--source-db "$$source_copy" \
		--output-dir "$$output_dir" \
		--label release-docker
