#!/bin/sh
set -eu

secret_file="${FINELOR_SESSION_SECRET_FILE:-/app/.finelor/session.secret}"

needs_secret=0

case "${SESSION_SECRET:-}" in
"" | *'${'* | \<auto-generated* | \<replace*)
    needs_secret=1
    ;;
*)
    if [ "${#SESSION_SECRET}" -lt 64 ]; then
        needs_secret=1
    fi
    ;;
esac

if [ "$needs_secret" -eq 1 ]; then
    mkdir -p "$(dirname "$secret_file")"

    if [ ! -s "$secret_file" ]; then
        umask 077
        head -c 96 /dev/urandom | base64 | tr -d '\n' >"$secret_file"
    fi

    SESSION_SECRET="$(cat "$secret_file")"
    export SESSION_SECRET
fi

exec "$@"
